
services:

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - app-network

  grafana:
    hostname: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - app-network
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  consul:
    image: hashicorp/consul:1.19
    ports:
      - "8500:8500"
    networks:
      - app-network
    command: "agent -dev -client=0.0.0.0"
    

  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./auth_service/.env
    container_name: auth_service
    depends_on:
      - postgres_auth
      - consul
    links:
      - postgres_auth
    networks:
      - app-network


  session_service1:
    build:
      context: ./session_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./session_service/.env
    container_name: session_service1
    depends_on:
      - postgres_sesh
      - consul
    links:
      - postgres_sesh
    networks:
      - app-network

  session_service2:
    build:
      context: ./session_service
      dockerfile: Dockerfile
    ports:
      - "5002:5001"
    env_file:
      - ./session_service/.env
    container_name: session_service2
    depends_on:
      - postgres_sesh
      - consul
    links:
      - postgres_sesh
    networks:
      - app-network

  session_service3:
    build:
      context: ./session_service
      dockerfile: Dockerfile
    ports:
      - "5003:5001"
    env_file:
      - ./session_service/.env
    container_name: session_service3
    depends_on:
      - postgres_sesh
      - consul
    links:
      - postgres_sesh
    networks:
      - app-network

  gateway:
    build: ./gateway
    ports:
      - "3001:3001"
    depends_on:
      - auth_service
      - session_service1
      - session_service2
      - session_service3
      - consul
    environment:
      - CONSUL_HOST=consul
    networks:
      - app-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app-network

  postgres_auth:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: AuthDB
    networks:
      - app-network
    ports:
      - "5434:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data

  postgres_sesh:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: SessionDB
    networks:
      - app-network
    ports:
      - "5435:5432"
    volumes:
      - postgres_session_data:/var/lib/postgresql/data

volumes:
  postgres_user_data:
  postgres_session_data:
  prometheus_data:
  grafana_data:

networks:
  app-network:
    driver: bridge
